version: '2'

services:
  orderer.example.com:
    image: hyperledger/fabric-orderer:latest
    environment:
      - ORDERER_GENERAL_LOGLEVEL=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
    ports:
      - 7050:7050

  peer0.manufacturer.example.com:
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_PEER_ID=peer0.manufacturer.example.com
      - CORE_PEER_ADDRESS=peer0.manufacturer.example.com:7051
      - CORE_PEER_LOCALMSPID=ManufacturerMSP
    ports:
      - 7051:7051

  peer0.distributor.example.com:
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_PEER_ID=peer0.distributor.example.com
      - CORE_PEER_ADDRESS=peer0.distributor.example.com:8051
      - CORE_PEER_LOCALMSPID=DistributorMSP
    ports:
      - 8051:8051

  peer0.retailer.example.com:
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_PEER_ID=peer0.retailer.example.com
      - CORE_PEER_ADDRESS=peer0.retailer.example.com:9051
      - CORE_PEER_LOCALMSPID=RetailerMSP
    ports:
      - 9051:9051

  cli:
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    depends_on:
      - orderer.example.com
      - peer0.manufacturer.example.com
      - peer0.distributor.example.com
      - peer0.retailer.example.com
